apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-spl-be
  labels:
    app: prod-spl-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-spl-be
  template:
    metadata:
      labels:
        app: prod-spl-be
    spec:
      containers:
        - name: prod-spl-be
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "3000"
          envFrom:
            - secretRef:
                name: prod-spl-be
          ports:
            - name: express
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: express
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: express
            initialDelaySeconds: 30
            periodSeconds: 2
